pixijs/filters

src/pixelate/PixelateFilter.js
this change fixes `PixelateFilter` in the example app.
as it turned out, the filter is fixed by simply assigning the new value to `uniforms.size` instead of `uniforms.size.value`.
I'm sad to admit that I don't yet know enough about pixi.js to describe why this works or why the previous implementation was broken.
=> fix Pixelate filter

filters/ascii/src/AsciiFilter.js, filters/bloom/src/BloomFilter.js, filters/bulge-pinch/src/BulgePinchFilter.js, filters/color-replace/src/ColorReplaceFilter.js, filters/convolution/src/ConvolutionFilter.js, filters/cross-hatch/src/CrossHatchFilter.js, filters/dot/src/DotFilter.js, filters/drop-shadow/src/DropShadowFilter.js, filters/emboss/src/EmbossFilter.js, filters/glow/src/GlowFilter.js, filters/outline/src/OutlineFilter.js, filters/pixelate/src/PixelateFilter.js, filters/rgb-split/src/RGBSplitFilter.js, filters/shockwave/src/ShockwaveFilter.js, filters/simple-lightmap/src/SimpleLightmapFilter.js, filters/tilt-shift/src/TiltShiftAxisFilter.js, filters/tilt-shift/src/TiltShiftFilter.js, filters/tilt-shift/src/TiltShiftXFilter.js, filters/tilt-shift/src/TiltShiftYFilter.js, filters/twist/src/TwistFilter.js, package.json, tools/build/index.js
Fixes #32 
The **es** build now includes setting the `PIXI` namespace for filters. Previously, only the **umd** supported this.
=> Better PIXI Namespace Definitions

.travis.yml, README.md, package.json, scripts/jsdoc.conf.json
These are small housekeeping fixes that affect the build process and Travis, nothing to do with the filters themselves.
* Changes NPM `postinstall` to run lerna’s bootstrap instead of bootstrap pre-running with `npm install`, to remove developer confusion. (context: #45 and https://github.com/pixijs/pixi-filters/pull/40#issue-259329927)
* Created a simpler version of JSDoc include, so that we don’t have add every new filter.
=> Housekeeping Fixes

filters/all/package.json, filters/ascii/package.json, filters/bloom/package.json, filters/bulge-pinch/package.json, filters/color-replace/package.json, filters/convolution/package.json, filters/cross-hatch/package.json, filters/dot/package.json, filters/drop-shadow/package.json, filters/emboss/package.json, filters/glow/package.json, filters/outline/package.json, filters/pixelate/package.json, filters/rgb-split/package.json, filters/shockwave/package.json, filters/simple-lightmap/package.json, filters/tilt-shift/package.json, filters/twist/package.json, filters/zoom-blur/package.json
The version in the output, published file is not correctly matching the version in **package.json**, although the contents of the file are correct.
After researching Lerna and NPM prepublishing hooks, I discovered that packages were not being built immediately before publish. Seems there is [some disagreement](https://github.com/lerna/lerna/pull/499#issuecomment-324100681) exactly how to replicate NPM's `prepublish` (or `prepare`/`prepublishOnly` for NPM +4) in Lerna's `publish` lifecycle so decided to use `postversion` instead.
This change builds using the `postversion` hook in the Lerna [publishing lifecycle](https://github.com/lerna/lerna/blob/master/src/commands/PublishCommand.js#L623).
=> Make sure filters are rebuilt-after version bump

tools/screenshots/renderer.js
Sometimes , the filter with `required arguments` ,  call `new FilterClass()` directly will take some errors.
If add `obj.arguments` feature , filter developer could  add arguments in  config.json like this: 
```
{
"name": "MultiColorReplaceFilter",
"filename": "multi-color-replace",
"arguments": [
[3238359, 938417, 1464209],
[16711680, 65280, 16776960],
0.2
]
},
```
=> Add obj.arguments for `required arguments`

examples/index.html, filters/advanced-bloom/src/AdvancedBloomFilter.js, filters/advanced-bloom/src/ExtractBrightnessFilter.js, filters/advanced-bloom/src/advanced-bloom.frag, filters/advanced-bloom/src/extract-brightness.frag, filters/advanced-bloom/types.d.ts, filters/all/types.d.ts
Rename some properties ( read unreal engine doc for reference): 
```
brightness --> bloomScale : 
because this property is only for changing the bloom's strength, not the overall brightness.
```
```
contrast --> brightness: 
because this property will change the overall brightness , not contrast
```
=> Rename some properties & update some annotations

filters/multi-color-replace/src/MultiColorReplaceFilter.js
I suggest the developers of PIXI team could install some plugins for `remove trailing-white-space` in their code editor.
BTW , I use sublime text 3 , the feature built in it.
=> Remove trailing-white-space

filters/zoom-blur/src/zoom-blur.frag
On some Android device , the webgl doesn't support that  compute variable with uniform parames in global scope.
Must move them in a function.
=> Fix bug on some Android device.

bundle/types.d.ts, filters/advanced-bloom/types.d.ts, filters/ascii/types.d.ts, filters/bloom/types.d.ts, filters/bulge-pinch/types.d.ts, filters/color-replace/types.d.ts, filters/convolution/types.d.ts, filters/cross-hatch/types.d.ts, filters/dot/types.d.ts, filters/drop-shadow/types.d.ts, filters/emboss/types.d.ts, filters/glow/types.d.ts, filters/godray/types.d.ts, filters/multi-color-replace/types.d.ts, filters/outline/types.d.ts, filters/pixelate/types.d.ts, filters/rgb-split/types.d.ts, filters/shockwave/types.d.ts, filters/simple-lightmap/types.d.ts, filters/tilt-shift/types.d.ts, filters/twist/types.d.ts, filters/zoom-blur/types.d.ts
This fixes compatibility with [pixi.js typings](https://github.com/pixijs/pixi-typescript/blob/v4.x/pixi.js.d.ts#L1290) where Filter requires the uniform data template. 
We have explicitly decided not to document uniforms in **pixi-filters** because we want people to use the API properties instead.
Discovered this when creating [Rollup + TypeScript Example](https://github.com/pixijs/pixi-filters/wiki/Rollup---TypeScript-Example)
=> Fixes Typings

tools/demo/src/DemoApplication.js
I add this property for stopping fish & pond only.
The stop  shader & fish & pond , this feature will look like as same as `stop rendering`
So  I hope still run  `this.animateTimer += 0.1 * delta` & ` this.events.emit('animate', delta, animateTimer)`
=> Don't stop shader , when fish & pond are stopped

bundle/types.d.ts, filters/outline/README.md, filters/outline/src/OutlineFilter.js, filters/outline/src/outline.frag, filters/outline/types.d.ts, tools/demo/src/filters/outline.js
* add a new argument: `quality`
* use ANGLE_STEP(quality, sample) instead of THICKNESS ( they are different things)
* fix bug about #107 
* optimal performance (just  a little) 
* update outline's demo
=> Improve OutlineFilter

filters/glow/src/glow.frag
Hi.
I used  glow-filter in my project and found the glow-filter could not work in some mobile broswer, those broswers thrown following message:
>S0012: Global variable initializer must be a constant expression.
Then i found in your code you put `const float PI...` in `main` function and let an no-constant variable `px` out of `main` function, it's the reason for this PR.
=> Fixed bugs of fragment shader in glow-fliter.

bundle/package.json, filters/color-map/src/ColorMapFilter.js, lerna.json, package.json, rollup.config.js, tools/demo/package.json, tools/demo/rollup.config.js
* Updates Rollup, Lerna and plugin dependencies
* Updates to new Rollup config format
* Removes `postversion` hack from Lerna < 2.7.0
* Fixes issue with setting `colorMap` with ColorMapFilter and v5
=> Updates all dependencies, fixes colormap for v5

filters/glitch/src/GlitchFilter.js
updateID will be changed when call  ```texture.baseTexture.emit('update', texture.baseTexture);```
=> Remove needless code

bundle/types.d.ts, filters/motion-blur/src/MotionBlurFilter.js, filters/motion-blur/types.d.ts, tools/demo/src/filters/motion-blur.js
Fixes #161 
* MotionBlur's velocity property is now a `PIXI.ObservablePoint` so that changes automatically update the uniforms without needing to resetting `velocity`
=> Adds support for velocity being an ObservablePoint

filters/bulge-pinch/src/BulgePinchFilter.js
Fixes issue that ignores if 0 is passed as "radius" or "strength".
```
this.radius = radius || 100 // 0 is evaluated as "false" and being ignored
```
=> Allow 0 as radius and strength argument

filters/color-map/src/color-map.frag
Properly fixes the color-map frag shader.
Uses all 3 xyz offsets to properly adjust color.
Allows sprite alpha and fixes pre-mulitply
related to #171 
and fixes issues with #179 (I'd have modified his pr but I didn't know how)
=> Update color-map.frag to fix LUT bind issues

filters/zoom-blur/src/zoom-blur.frag
this is what I found recently, really good one: http://byteblacksmith.com/improvements-to-the-canonical-one-liner-glsl-rand-for-opengl-es-2-0/
so I created this PR to solve the issue I posted before: #170, or perhaps #139 is related too? actually everywhere if you want to use random, please use this hash generator instead of the old one.
changes: 
1. use new way to generate hash, old one does not work on iOS devices
2. remove the division for pre-multiplied alpha, it's even not enabled before in the `for` loop, why I need to divide the color by it's alpha at the end? this will cause the pixel too bright.
maybe some other shaders of this project have the old hash method too (it's really common on internet, everywhere....), so you might replace all of them with this new one.
test for …
=> new way for hash generation

filters/ascii/src/ascii.frag
This fixes the bug described in #173 by avoiding the use a certain type of condition with which some old (macOS) WebGL compilers have troubles.
=> Fix #173 AsciiFilter bug due to an old WegGL compiler bug

filters/glitch/src/glitch.frag
Thanks to @rtalon83 I found that we just cant use `texture2D` inside one of `if` branches.
Win7 and Win8.1 d3d doesnt like that.
=> Fix glitch filter for win7 d3d

README.md, bundle/README.md, bundle/package.json, bundle/src/index.js, bundle/types.d.ts, filters/color-overlay/LICENSE, filters/color-overlay/README.md, filters/color-overlay/package.json, filters/color-overlay/src/ColorOverlayFilter.js, filters/color-overlay/src/colorOverlay.frag, filters/color-overlay/src/index.js, filters/color-overlay/types.d.ts, tools/demo/src/filters/color-overlay.js, tools/demo/src/filters/index.js, tools/screenshots/config.json
The ColorOverlayFilter replaces all colors within a source graphic with a single color, respecting the alpha channel of the source graphic. See attached graphic for visual example:
=> Add ColorOverlayFilter

filters/drop-shadow/src/dropshadow.frag
The results of the operation were not used and immediately overwritten
=> Remove unncessary if in drop shadow frag shader

filters/bulge-pinch/src/BulgePinchFilter.js, filters/bulge-pinch/types.d.ts, filters/zoom-blur/src/ZoomBlurFilter.js, filters/zoom-blur/types.d.ts, tools/demo/src/filters/zoom-blur.js
These particular filters (BulgePinchFilter and ZoomBlurFilter) had 3 or more constructor arguments that had defaults but where the order didn't make much logic sense. This PR provide alternative constructor options that can be set instead of flat arguments. Non-breaking, but encourages the use of the options by only documenting options.
=> Provide options for bulge-pinch and zoom-blur

filters/outline/src/OutlineFilter.js
1. remove `shader` field usage
2. remove awful red color, take color from https://pixijs.io/examples/#/plugin-filters/outline.js
=> OutlineFilter doc fix

package.json
Publish exact version of all workspace deps so specific version in consumers projects will be honored
In similar manner as in: https://github.com/pixijs/pixi.js/pull/6211
package.json:
Error: 
` TS2554: Expected 0-1 arguments, but got 5.`
Looks like I'm downloading pixi filters 3.1.0 instead of 3.0.3
=> Publish exact version of all internal deps

filters/advanced-bloom/src/AdvancedBloomFilter.js, filters/drop-shadow/src/DropShadowFilter.js, filters/kawase-blur/src/KawaseBlurFilter.js
Fixes #251
Converting `clear` to a number supports both <5.3.0 and >=5.3.0. This property was converted to a constant `CLEAR_MODES`, this seemed like easy solution to ignore the deprecation warnings.
=> Convert clear to clearModes to be compatible with 5.3.0+

filters/godray/src/GodrayFilter.js, filters/godray/src/gorday.frag, filters/godray/types.d.ts, filters/kawase-blur/src/KawaseBlurFilter.js, tools/demo/src/filters/godray.js
Addresses issue #262 
[add] Support for alpha including setter and getter to godray filter
[update] types accordingly
[update] tools/demo to include controls for `alpha`
Feel free to squash - I have an aggressive prettier config and had to fight it to get the formatting to match up better to avoid a noisy PR.
=> Add alpha support to godray filter

filters/crt/src/crt.frag
* the `dir` should  `vTextureCoord - centerPoint` first.
* some codes only be used  when `lineWidth > 0.0`
=> fix a bug about `dir` and a little cosmetic

filters/kawase-blur/src/KawaseBlurFilter.js
There is currently not padding automatically applied to this filter, which can be confusing.
I have added a basic padding calc
=> Added basic padding to kawase blur

filters/twist/package.json, filters/twist/src/TwistFilter.js, filters/twist/types.d.ts
This was annoying me and made this filter clunky to use. Related issue #244. The constructor options are because I wanted to include offset and the constructor arguments order didn't make sense in terms of importance.
* Supports passing `offset` as a constructor option
* Set's initial `offset` Point by default
* Deprecates the constructor spread `(radius, angle, padding)`
* Favors the use of constructor options
=> Support passing offset in TwistFilter constructor

filters/glitch/src/GlitchFilter.ts
#299 
On line 109 GlitchFilter initialized the `this._direction` variable to zero.
This variable is the internal version of a setter `direction` that also writes the uniform `cosDir` and `sinDir` values **as long as the new `direction` value is different to the one in `_direction`**
Initializing `_direction` to zero makes the filter ignore when the direction is set to zero again thus never setting the `cosDir` and `sinDir` variable in the shader.
This PR un-initializes the `this._direction` as it will be initialized in the constructor via the setter `direction` anyway.
=> Fixed glitch filter by un-initializing a variable

filters/advanced-bloom/src/AdvancedBloomFilter.ts, filters/drop-shadow/src/DropShadowFilter.ts
Follow-up to https://github.com/pixijs/pixijs/pull/7769.
When building with `typescript ^4.0.0` and `pixi ^6.1.3`, `AdvancedBloomFilter` and `DropShadowFilter` both complain about a protected property (`_resolution`) being overwritten by a private property.
This eliminates that error and doesn't seem to break anything for older versions of `typescript` or `pixi`.
=> Update _resolution to be protected instead of private

README.md, bundle/README.md
* Made sure it said "PixiJS v7", instead of v5
* Add GrayscaleFilter to READMEs
=> Chore: Update README typos, missing GrayscaleFilter

bundle/package.json, rollup.config.js
Closes #326
Adds a new .mjs output file for the `pixi-filters` package to support [importmap](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script/type/importmap) ([browser support](https://caniuse.com/import-maps)).
For example:
```html
<body>
<script type="importmap">
{
"imports": {
"pixi.js": "https://cdn.jsdelivr.net/npm/pixi.js@7.x/dist/pixi.min.mjs",
"@pixi": "https://cdn.jsdelivr.net/npm/pixi.js@7.x/dist/pixi.min.mjs",
"pixi-filters": "https://filters.pixijs.download/feature/browser-module/pixi-filters.mjs"
}
}
</script>
<script type="module">
import {Application, Sprite, Texture} from "pixi.js";
import {GlowFilter} from "pixi-filters";
const app = new Application();
document.body.appendChild(app.view);
const sprite = app.stage.addChild(new Sprite(Texture.WHITE)); …
```
=> Output a browser bundle for pixi-filters

filters/ascii/src/ascii.frag
Since the original shader was made for shadertoy where the canvas origin is bottom-left, the characters were upside-down.
This was fixed by simply removing the minus in the character sampling function (line 35).
I've also adjusted the brightness calculation of the sampled pixel color to reflect the variing intensities of color components as they are perceived by the human eye. This change alters the appearance of the result a little but should give better mappings of characters to their source pixels.
fixes #325
=> Fixed flipped characters in AsciiFilter

package.json
We shouldn't allow lint warnings on CI. This will error (fail) PRs that have lint warnings.
=> Disallow warning with linting

filters/tilt-shift/src/TiltShiftAxisFilter.ts, filters/tilt-shift/src/TiltShiftFilter.ts
Make TiltShiftFilter more inline with other filters constructor
* `new TiltShiftFilter(blur, gradientBlur, start, end)` becomes `new TiltShiftFilter({ blur, gradientBlur, start, end})`
=> Convert TiltShiftFilter constructor arguments to options

filters/drop-shadow/src/DropShadowFilter.ts, tools/demo/src/filters/drop-shadow.js, tools/screenshots/config.json
Closes #256
* Deprecated `rotation` and `distance` from DropShadowFilter in favor of `offset.x` and `offset.y`
```js
import { DropShadowFilter } from '@pixi/filters-drop-shadow';
// Set with constructor options
const filter = new DropShadowFilter({
offset: { x: 2, y: 2 }, // can also be Point
});
// Set with the offset member
filter.offset.set(4, 4);
```
=> Use x/y offset for the DropShadowFilter instead of rotation/distance

filters/hsl-adjustment/src/hsladjustment.frag
**Saturation**: Use linear calcuation for negative values (desaturate) and non-linear `(1.-1./(1.001-x))` for positive values (saturate). This allows extreme color values and works better with the `colorize` option.
Comparison - new (left) vs current (right):
**Lightness**: Mix black/white instead of add (same as photoshop/photopea).
=> HslAdjustmentFilter: Update calculations of saturation and lightness

filters/color-gradient/src/ColorGradientFilter.ts, filters/color-gradient/src/colorGradient.frag, tools/demo/src/filters/color-gradient.js
This PR allows color-gradient to replace the original colors.
Preserves backwards compatibility.
This is useful for e.g. drawing a gradient that fades to transparent - in this case the original color of the pixels should be discarded.
=> Feature: Allow color-gradient to replace original colors

src/adjustment/AdjustmentFilter.ts, src/advanced-bloom/ExtractBrightnessFilter.ts, src/bevel/BevelFilter.ts, src/color-gradient/ColorGradientFilter.ts, src/cross-hatch/CrossHatchFilter.ts, src/crt/CRTFilter.ts, src/glow/GlowFilter.ts, src/grayscale/GrayscaleFilter.ts, src/hsl-adjustment/HslAdjustmentFilter.ts, src/tilt-shift/TiltShiftAxisFilter.ts, src/twist/TwistFilter.ts
=> Chore: Use `Program.from` for Caching

src/advanced-bloom/AdvancedBloomFilter.ts, src/ascii/AsciiFilter.ts, src/bulge-pinch/BulgePinchFilter.ts, src/color-map/ColorMapFilter.ts, src/color-overlay/ColorOverlayFilter.ts, src/color-replace/ColorReplaceFilter.ts, src/convolution/ConvolutionFilter.ts, src/dot/DotFilter.ts, src/drop-shadow/DropShadowFilter.ts, src/emboss/EmbossFilter.ts, src/glitch/GlitchFilter.ts, src/godray/GodrayFilter.ts, src/kawase-blur/KawaseBlurFilter.ts, src/motion-blur/MotionBlurFilter.ts, src/multi-color-replace/MultiColorReplaceFilter.ts, src/old-film/OldFilmFilter.ts, src/outline/OutlineFilter.ts, src/pixelate/PixelateFilter.ts, src/radial-blur/RadialBlurFilter.ts, src/reflection/ReflectionFilter.ts, src/rgb-split/RGBSplitFilter.ts, src/shockwave/ShockwaveFilter.ts, src/simple-lightmap/SimpleLightmapFilter.ts, src/zoom-blur/ZoomBlurFilter.ts
Follow-up to #438, completes for all filters
All the current PRs involve this change, would be better to get this out universally rather than one-by-one.
=> Chore: Use Program.from for Caching, Part 2

src/advanced-bloom/AdvancedBloomFilter.ts
- Add deprecations for the Advanced Bloom filter.
- Use `GpuProgram.from` and `GlProgram.from` for caching.
=> Chore: Advanced Bloom Filter Deprecations

src/ascii/AsciiFilter.ts
- Add deprecations for the ASCII filter.
- Use `GpuProgram.from` and `GlProgram.from` for caching.
=> Chore: ASCII Filter Deprecations

src/bulge-pinch/BulgePinchFilter.ts
- Add deprecations for the Bulge Pinch filter.
=> Chore: Bulge Pinch Filter Deprecations

src/color-overlay/ColorOverlayFilter.ts
- Add deprecations for the Color Overlay filter.
=> Chore: Color Overlay Filter Deprecations

src/convolution/ConvolutionFilter.ts, src/convolution/convolution.frag, src/convolution/convolution.wgsl
- Add deprecations for the Convolution filter.
=> Chore: Convolution Filter Deprecations

src/dot/DotFilter.ts
- Add deprecations for the Dot filter.
=> Chore: Dot Filter Deprecations

src/drop-shadow/DropShadowFilter.ts
- Add deprecations for the Drop Shadow filter.
=> Chore: Drop Shadow Filter Deprecations

src/emboss/EmbossFilter.ts
- Simplify single param option.
=> Chore: Emboss Filter Tweaks

src/glitch/GlitchFilter.ts
- Add deprecations for the Glitch filter.
=> Chore: Glitch Filter Deprecations

src/kawase-blur/KawaseBlurFilter.ts
- Add deprecations for the Kawase Blur filter.
=> Chore: Kawase Blur Filter Deprecations

src/multi-color-replace/MultiColorReplaceFilter.ts
- Add deprecations for the Multi-Color Replace filter.
=> Chore: Multi-Color Replace Filter Deprecations

examples/src/filters/old-film.mjs, src/old-film/OldFilmFilter.ts, src/old-film/old-film.frag, src/old-film/old-film.wgsl
- Add deprecations for the Old Film filter.
=> Chore: Old Film Filter Tweaks

src/outline/OutlineFilter.ts
- Add deprecations for the Outline filter.
=> Chore: Outline Filter Deprecations

src/rgb-split/RGBSplitFilter.ts
- Add deprecations for the RGB Split filter.
=> Chore: RGB Split Filter Deprecations

src/simple-lightmap/SimpleLightmapFilter.ts
- Add deprecations for the Simple Lightmap filter.
=> Chore: Simple Lightmap Filter Deprecations

src/zoom-blur/ZoomBlurFilter.ts
- Add deprecations for the Zoom Blur filter.
=> Chore: Zoom Blur Filter Deprecations

examples/src/DemoApplication.mjs, examples/src/filters/backdropBlur.mjs, examples/src/filters/index.mjs, src/backdrop-blur/BackdropBlurFilter.ts, src/backdrop-blur/backdrop-blur-blend.frag, src/backdrop-blur/backdrop-blur-blend.wgsl, src/backdrop-blur/index.ts, src/index.ts
Adds a backdrop blur filter which will blur the background behind an object and then draw the object on top of it, creating a frosted glass-like look.
The filter tries to reuse as much of the original `BlurFilter` as possible. Currently it needs to access a private field of `FilterSystem` to get ahold fo the `backTexture`, so a change in pixi.js exposing the backTexture as public  is probably required.
For the demo, this filter relies on the objects being transparent, so it won't have an effect without lowering the fish' alpha.
Also missing a screenshot config for the docs currently since that relies on the transparent fish.
`blendRequired` in combination with `padding` will currently crash the webgpu renderer, so I'm setting padding to 0 right now, once that's fixed that can be removed. …
=> Add backdrop blur filter

package-lock.json
Bumping extension-scripts solves two issues:
* Publishing not working correctly (`NODE_AUTH_TOKEN `not getting passed along to `npm publish`)
* Processes with a non-zero result not passing along the result
=> Chore: Bump extension-scripts

examples/src/filters/tilt-shift.mjs, src/tilt-shift/TiltShiftAxisFilter.ts, src/tilt-shift/TiltShiftFilter.ts, src/tilt-shift/tilt-shift.frag, src/tilt-shift/tilt-shift.wgsl
Fixes #463
* Removes `window.innerWidth` and `window.innerHeight` references
* Standardizes around `uDimensions` name for texture size like other filters
* Consistently updates `uDelta` correctly
* [webgl](https://filters.pixijs.download/fix/tilt-shift/examples/index.html?enabled=TiltShiftFilter&preference=webgl)
* [webgpu](https://filters.pixijs.download/fix/tilt-shift/examples/index.html?enabled=TiltShiftFilter&preference=webgpu)
=> fix: Remove window references from TiltShiftFilter

package.json
This PR adds `sideEffect: false` to the package json to allow for bundlers to correctly tree shake the library when using the default export e.g.
`import { XYZ } from 'pixi-filters';`
Before: 
After:
=> fix: tree shaking when using default import

README.md, examples/src/filters/index.mjs, examples/src/filters/simplex-noise.mjs, package.json, scripts/screenshots/config.json, src/index.ts, src/simplex-noise/SimplexNoiseFilter.ts, src/simplex-noise/index.ts, src/simplex-noise/simplex.frag, src/simplex-noise/simplex.wgsl
Added simplex noise filter.
Filter creates a noise map and multiplies the current texture with it. 
https://github.com/user-attachments/assets/801d85af-601a-45f6-875a-80632eecb694
=> Added Simplex Noise Filter

src/tilt-shift/TiltShiftAxisFilter.ts, src/tilt-shift/TiltShiftFilter.ts, src/tilt-shift/tilt-shift.frag, src/tilt-shift/tilt-shift.wgsl
=> Bug: TiltShiftFilter coordinates are calculated incorrectly

examples/index.html
We should be using the latest v8 in dev, not `next-v8` which is no longer maintained
=> chore: Use the latest v8 in example

src/motion-blur/motion-blur.wgsl
Previously the motion blur webGL and webGPU shaders were inconsistent: webGL used i32 and webGPU used f32 for uKernelSize. 
The filter passes the uKernelSize in as an i32. This broke the webGPU shader since it expected an f32. Now uKernelSize is an i32 everywhere.
=> Changed uKernelSize from f32 to i32 in MotionBlur WebGPU shader
