pixijs/filters

package.json

* Updates to the latest **pixify** (v1.4.0) to support watching
* Adds watching (`npm start`) with linting

Improves the watch command

---

examples/index.html

fix pixi.js library reference

---

src/rgb/RGBSplitFilter.js

fixed issue https://github.com/pixijs/pixi-filters/issues/17

BugFix: In RGBSplitFilter blue doesn't moves fixed

---

examples/index.html
filters/all/types.d.ts
filters/zoom-blur/src/ZoomBlurFilter.js
filters/zoom-blur/src/zoom-blur.frag
filters/zoom-blur/types.d.ts

Bug:
The raduis rendered is not as same as user set.
The wrong resolution.
Update:
Don't allow set custom size anymore. it's useless & would take some bugs.

Fix bugs of ZoomBlure about resolution & size

---

.travis.yml
filters/ascii/src/AsciiFilter.js
filters/bulge-pinch/src/BulgePinchFilter.js
filters/drop-shadow/src/DropShadowFilter.js
filters/glow/src/GlowFilter.js
filters/pixelate/src/PixelateFilter.js
filters/tilt-shift/src/TiltShiftFilter.js
tools/screenshots/renderer.js

Remove trailing-white-space

---

filters/zoom-blur/src/ZoomBlurFilter.js
filters/zoom-blur/src/zoom-blur.frag

Use `-1` or Infinity replace `1E8`.

Change the default value of `radius`

---

filters/bulge-pinch/src/BulgePinchFilter.js
filters/shockwave/src/ShockwaveFilter.js

Follow-up for https://github.com/pixijs/pixi.js/issues/4488

not all filters were passing fourth param in `applyFilter`

---

filters/outline/src/outline.frag

details at https://github.com/pixijs/pixi-filters/issues/107#issuecomment-355000854

Fix bug : #107

---

bundle/types.d.ts
filters/godray/src/GodrayFilter.js
filters/godray/src/gorday.frag
filters/godray/types.d.ts
tools/demo/src/filters/godray.js

More details at : https://github.com/pixijs/pixi-filters/issues/65

update GordayFilter: support non-parallel lights

---

tools/demo/index.html

jsdelivr is more fast for some countries

Change the CDN (jsdelivr) for  static files

---

filters/bulge-pinch/src/bulgePinch.frag
filters/godray/src/gorday.frag
filters/motion-blur/src/motion-blur.frag
filters/radial-blur/src/radial-blur.frag
filters/shockwave/src/shockwave.frag
filters/tilt-shift/src/tilt-shift.frag
filters/zoom-blur/src/zoom-blur.frag

fix the bug about gl_FragColor on iOS

---

README.md
bundle/README.md
bundle/package.json
bundle/src/index.js
bundle/types.d.ts
filters/bevel/LICENSE
filters/bevel/README.md
filters/bevel/package.json
filters/bevel/src/BevelFilter.js
filters/bevel/src/bevel.frag
filters/bevel/src/index.js
filters/bevel/types.d.ts
tools/demo/src/filters/bevel.js
tools/demo/src/filters/index.js
tools/screenshots/config.json

Parametrs for bevel filter:
- Angle of the light and shadow in degrees
- Tickness of the bevel
- Color of the light
- Alpha of the light
- Color of the shadow
- Alpha of the shadow
Updating angle in game tick:
Screenshots:
Without filter:
With filter:
Tools demo:

Adds BevelFilter

---

filters/motion-blur/src/motion-blur.frag
filters/radial-blur/src/radial-blur.frag

Remove non-constant expressions in global scope

---

bundle/types.d.ts
filters/drop-shadow/LICENSE
filters/drop-shadow/package.json
filters/drop-shadow/src/DropShadowFilter.js
filters/drop-shadow/types.d.ts
tools/demo/src/filters/drop-shadow.js

Use KawaseBlurFilter instead of BlurFilter

---

rollup.config.js

see https://github.com/pixijs/pixi-filters/issues/159#issuecomment-383446607

Remove `this` in dist  js file

---

filters/drop-shadow/src/DropShadowFilter.js
tools/demo/src/DemoApplication.js

+ fix DropShadowFilter, but we also have to patch v5 itself, default filter is wrong

Fix DemoApplication resize problem

---

bundle/types.d.ts
filters/drop-shadow/types.d.ts

Made properties in DropShadowFilterOptions optional to match docs

---

filters/convolution/src/ConvolutionFilter.js
tools/demo/src/filters/convolution.js

* Workaround IE 11 Float32Array bug (only create array once)
* Set defaults for ConvolutionFilter
* Support matrix setting in the demo

Fixes ConvolutionFilter

---

filters/glitch/src/GlitchFilter.js

Fixes slices not changing in v5

Fixes GlitchFilter

---

filters/drop-shadow/src/DropShadowFilter.js
filters/drop-shadow/src/dropshadow.frag

Fix dropshadow filter tint shift

---

filters/motion-blur/src/MotionBlurFilter.js

Fix v5 deprecation warning

---

filters/outline/src/OutlineFilter.js
tools/demo/src/filters/outline.js

Adds `padding` for OutlineFilter determined by the thickness

Add auto-padding based on the outline thickness

---

filters/drop-shadow/src/DropShadowFilter.ts

Fixes https://github.com/pixijs/filters/issues/302

Do not mutate default values.

---

.github/workflows/nodejs.yml

Related: https://github.com/pixijs/pixijs/pull/8953

Unblock Actions

---

filters/outline/src/OutlineFilter.ts
filters/outline/src/outline.frag
tools/demo/src/filters/outline.js

[outline_alpha.webm](https://user-images.githubusercontent.com/1616817/207908314-a1ceb7dd-ba52-4ffd-bcb9-194d5521447c.webm)

Add alpha setting to outline filter

---

filters/dot/src/DotFilter.ts
filters/dot/src/dot.frag
tools/demo/src/filters/dot.js

Closes #268.
[dot_grayscale.webm](https://user-images.githubusercontent.com/1616817/207953950-79be758b-b79e-48c6-aade-924b888b62c2.webm)

Add grayscale setting to dot filter

---

bundle/package.json
bundle/src/index.ts
filters/grayscale/LICENSE
filters/grayscale/README.md
filters/grayscale/package.json
filters/grayscale/src/GrayscaleFilter.ts
filters/grayscale/src/grayscale.frag
filters/grayscale/src/index.ts
package-lock.json
tools/demo/src/filters/grayscale.js
tools/demo/src/filters/index.js
tools/screenshots/config.json

Simple grayscale filter using [luminance](https://en.wikipedia.org/wiki/Luma_(video)) (CCIR 601).
```glsl
const vec3 weight = vec3(0.299, 0.587, 0.114); // r, g, b
```
[filter_grayscale.webm](https://user-images.githubusercontent.com/1616817/208238921-1f26b925-6d27-4793-8b28-540e6e707d81.webm)

Add grayscale filter

---

filters/glow/src/GlowFilter.ts
filters/glow/src/glow.frag
tools/demo/src/filters/glow.js

[glow_alpha.webm](https://user-images.githubusercontent.com/1616817/208251088-f61a1411-26b9-44bd-9b47-e4d117b83940.webm)

Add alpha setting to glow filter

---

README.md

Fix badge links and format filter demo links.

Chore: Readme cleanup

---

filters/hsl-adjustment/src/HslAdjustmentFilter.ts

* Minor improvements to defaults and constructor options for HslAdjustmentFilter
Before: https://filters.pixijs.download/main/docs/HslAdjustmentFilter.html
After: https://filters.pixijs.download/chore/hsl-docs/docs/HslAdjustmentFilter.html

Add more docs for HslAdjustmentFilter

---

filters/color-gradient/src/ColorGradientFilter.ts

ColorGradientFilter - Make alpha and maxColors optional when using CSS

---

.github/workflows/main.yml

I reverted the publish workflow to the v5 version.

Fix: Revert publish workflow

---

README.md

Fix: CDN URL is incorrect

---

examples/src/DemoApplication.mjs
scripts/screenshots/renderer.js

- Change default filter args option to be `undefined` to allow proper fallback.
- Fix rendering of animation screenshots.

Chore: Minor Tool Fixes

---

src/godray/GodrayFilter.ts

- Add deprecations for the God Ray filter.

Chore: God Ray Filter Deprecations

---

src/shockwave/shockwave.wgsl

fix the premultiply in shockwave filter

---

package-lock.json
package.json

Fix: Missing gradient-parser types

---

src/bevel/BevelFilter.ts

Fix: Remove double rotation calculation in Bevel

---

src/hsl-adjustment/HslAdjustmentFilter.ts

Fixes #467 
* Fix: Allows `saturation` and `lightness` to be set via constructor
* Chore: Additional cleanup

Fix: Allows saturation and lightness via HslAdjustmentFilter constructor

---

src/color-overlay/color-overlay.frag
src/color-overlay/color-overlay.wgsl

Would close #493.
An example of the changed shaders can be inspected [here](https://codepen.io/Albinkong/pen/EaxEwOa).

Mix color and alpha separately in ColorOverlayFilter

---

src/color-overlay/color-overlay.frag
src/color-overlay/color-overlay.wgsl

Fixes issue introduced in #494. Example can be found [here](https://codepen.io/Albinkong/pen/XJWELbJ).

Fix ColorOverlayFilter multiplier
